In [2]:
import sys
import json
import os
from collections import namedtuple
import numpy as np
from matplotlib import pyplot as plt

def read_json(pth):
    with open(pth, 'r') as f:
        return json.load(f)

def to_json(dct, pth):
    with open(pth, 'w') as f:
        return json.dump(dct, f)

def flip(p=0.5):
    return True if np.random.random() < p else False
eps = 0.75



loc  = lambda s: f"/home/ubuntu/vdp-tool-chain-repo/clevr-inference/gt_outputs/{s}/results.json"
loc2  = lambda s: f"/home/ubuntu/vdp-tool-chain-repo/data/inference-outputs/{s}/results.json"



In [16]:
mindist = lambda arr : all([abs(a-b) >= 1.0 for a in arr for b in arr if a != b])


In [30]:
puzzle_loc = loc2('alternate-color') 


Object = namedtuple('Object', ['x', 'y', 'z', 'size', 'shape', 'color', 'orientation', 'material'])
variables = read_json("data/properties.json")

material = 'rubber'
shape    = 'cylinder'
size     = 'large'
color    = 'red'


imgs = list()
dx = lambda : round(np.random.uniform(-0.5, 0.5), 2)
dy = lambda : round(np.random.uniform(-1.5, 1.5), 2)

puzzle = read_json(puzzle_loc)

# print(puzzle)

for i, img in enumerate(puzzle['scenes']):
    objects = img['objects']
    if not len(objects):
        continue
    num_objects = len(objects)
    thetas    = np.zeros(num_objects)
    zs = np.zeros(num_objects)
    xs = np.array([obj['position'][0] for obj in objects])
    ys = np.array([obj['position'][1] for obj in objects])

    xs = np.linspace(-2.75, 2.75, num_objects)[np.argsort(xs)] + dx()
    ys = np.zeros(num_objects) + dy()

    print(xs)
    print(ys)

    assert(mindist(xs))
    assert(mindist(ys))
    
    
    materials = np.array([obj['material'] for obj in objects])
    shapes    = np.array([obj['shape'] for obj in objects])
    sizes     = np.array([obj['size'] for obj in objects])
    colors    = np.array([obj['color'] for obj in objects])

    objects = [Object(*tup) for i, tup in enumerate(zip(xs, ys, zs, sizes, shapes, colors, thetas, materials))]

    img_dict = { 'objects' : [dict(o._asdict()) for o in objects]}
    imgs.append(img_dict)

name = os.path.basename(os.path.dirname(puzzle_loc))
to_json(imgs, f"/home/ubuntu/vdp-tool-chain-repo/data/clevr-puzzles/{name}.json")

[-3.2  2.3]
[-0.07 -0.07]
[-2.61  2.89]
[1. 1.]
[-3.07 -0.32  2.43]
[0.51 0.51 0.51]
[-2.49       -0.65666667  1.17666667  3.01      ]
[1.1 1.1 1.1 1.1]
[-2.4   -1.025  0.35   1.725  3.1  ]
[-0.72 -0.72 -0.72 -0.72 -0.72]
[-2.55       -0.71666667  1.11666667  2.95      ]
[0.43 0.43 0.43 0.43]
[-2.66  2.84]
[-1.14 -1.14]


[{'shape': 'cylinder', 'size': 'large', 'material': 'rubber', 'color': 'blue', 'position': [0.4225424826145172, 0.372123122215271, 0.6655023694038391]}, {'shape': 'cylinder', 'size': 'large', 'material': 'rubber', 'color': 'blue', 'position': [-1.7479301691055298, -2.006910800933838, 0.6890091300010681]}, {'shape': 'cylinder', 'size': 'large', 'material': 'rubber', 'color': 'red', 'position': [-0.6452366709709167, -0.8426610827445984, 0.6808547377586365]}, {'shape': 'cylinder', 'size': 'large', 'material': 'rubber', 'color': 'red', 'position': [1.4085478782653809, 1.6661666631698608, 0.6859357953071594]}]


IndexError: index 4 is out of bounds for axis 0 with size 4